import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import AppSidebar from "@/components/app-sidebar"
import TopBar from "@/components/topbar";

export const metadata: Metadata = {
  title: "Audio Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen grid grid-rows-[auto_1fr] grid-cols-[250px_1fr]">
      <div className="row-span-1 col-span-2 z-10">
        <TopBar />
      </div>

  
      <div className="row-span-2 z-0">
        <SidebarProvider> 
        <AppSidebar />
        <SidebarTrigger className="z-20" /> 
        </SidebarProvider>
      </div>

      <main className="row-span-2 overflow-auto p-4">
        
        {children}
      </main>
    </div>
      </body>
    </html>
  );
}
